# Documentation: http://docs.travis-ci.com/user/languages/julia/
language: julia
os:
  - linux
  - osx
# Force Ubuntu 18.04 "Bionic" to get even newer GCC, binutils etc.
dist: bionic
julia:
  - 1.1
  - 1.2
  - 1.3
  - 1.4
  - nightly
matrix:
  allow_failures:
    - julia: nightly
    - os: osx
  fast_finish: true
notifications:
  email:
    recipients:
      - mohamed.barakat@uni-siegen.de
    on_success: never   # default: change
    on_failure: always  # default: always
before_install:
#  - if [ "$TRAVIS_OS_NAME" = "linux" ]; then sudo apt-get update; fi # sudo apt-get install -y singular;
#  - if [ "$TRAVIS_OS_NAME" = "osx" ]; then brew update; fi # brew install singular
after_success:
  - julia -e 'using Pkg; Pkg.add("Coverage"); using Coverage; Codecov.submit(process_folder())'
#  - julia -e 'using Pkg; Pkg.add("Coverage"); using Coverage; Coveralls.submit(process_folder())'
script:
  - travis_wait 60 julia -e 'using Pkg;
          Pkg.instantiate();
          Pkg.test("HomalgProject");'
jobs:
  include:
    - stage: Documentation
      julia: 1.3
      script: julia --project=docs -e '
          using Pkg;
          Pkg.develop(PackageSpec(path=pwd()));
          Pkg.instantiate();
          include("docs/make.jl");'
      after_success: skip
