name = "HomalgProject"
uuid = "50bd374c-87b5-11e9-015a-2febe71398bd"
authors = ["Mohamed Barakat <mohamed.barakat@uni-siegen.de>"]
version = "0.2.2"

[deps]
GAP = "c863536a-3901-11e9-33e7-d5cd0df7b904"
Singular = "bcd08a7b-43d2-5ff7-b6d4-c458787f915c"
#LinearAlgebra = "37e2e46d-f89d-539d-b4ee-838fcccc9c8e" ## needed by JuliaExperimental

[compat]
julia = "1.3"
GAP = "^0"
Singular = "^0.2"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"
Documenter = "e30172f5-a6a5-5a46-863b-614d45cd2de4"

[targets]
test = ["Test","Documenter"]
